addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.2")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                  % "0.2.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"              % "1.1.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.9.7")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"               % "5.6.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.5.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
