addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.6")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                  % "0.2.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"              % "1.4.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.12.2")
addSbtPlugin("com.github.sbt"     % "sbt-header"               % "5.11.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.20.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
