addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                  % "0.2.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"              % "1.4.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.11.1")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"               % "5.10.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
